const WORD_BANK = [
  "the", "of", "and", "to", "a", "in", "for", "is", "on", "that", "by", "this", "with",
  "you", "it", "not", "or", "be", "are", "from", "at", "as", "your", "all", "have", "new",
  "more", "an", "was", "we", "will", "home", "can", "us", "about", "if", "page", "my",
  "has", "search", "free", "but", "our", "one", "other", "do", "no", "information", "time",
  "they", "site", "he", "up", "may", "what", "which", "their", "news", "out", "use", "any",
  "there", "see", "only", "so", "his", "when", "contact", "here", "business", "who", "web",
  "also", "now", "help", "get", "view", "online", "first", "am", "been", "would", "how",
  "were", "me", "services", "some", "these", "click", "its", "like", "service", "than", "find",
  "price", "date", "back", "top", "people", "had", "list", "name", "just", "over", "state",
  "year", "day", "into", "email", "two", "health", "world", "re", "next", "used", "go", "work",
  "last", "most", "products", "music", "buy", "data", "make", "them", "should", "product",
  "system", "post", "her", "city", "add", "policy", "number", "such", "please", "available",
  "copyright", "support", "message", "after", "best", "software", "then", "jan", "good", "video",
  "well", "where", "info", "rights", "public", "books", "high", "school", "through", "each",
  "links", "she", "review", "years", "order", "very", "privacy", "book", "items", "company",
  "read", "group", "sex", "need", "many", "user", "said", "de", "does", "set", "under",
  "general", "research", "university", "january", "mail", "full", "map", "reviews", "program",
  "life", "know", "games", "way", "days", "management", "part", "could", "great", "united",
  "hotel", "real", "item", "international", "center", "ebay", "must", "store", "travel",
  "comments", "made", "development", "report", "off", "member", "details", "line", "terms",
  "before", "hotels", "did", "send", "right", "type", "because", "local", "those", "using",
  "results", "office", "education", "national", "car", "design", "take", "posted", "internet",
  "address", "community", "within", "states", "area", "want", "phone", "dvd", "shipping",
  "reserved", "subject", "between", "forum", "family", "long", "based", "code", "show", "even",
  "black", "check", "special", "prices", "website", "index", "being", "women", "much", "sign",
  "file", "link", "open", "today", "technology", "south", "case", "project", "same", "pages",
  "version", "section", "own", "found", "sports", "house", "related", "security", "both", "county",
  "american", "game", "members", "power", "while", "care", "network", "down", "computer", "systems",
  "three", "total", "place", "end", "following", "download", "him", "without", "per", "access",
  "think", "north", "resources", "current", "posts", "big", "media", "law", "control", "water",
  "history", "pictures", "size", "art", "personal", "since", "including", "guide", "shop", "directory",
  "board", "location", "change", "white", "text", "small", "rating", "rate", "government", "children",
  "during", "usa", "return", "students", "shopping", "account", "times", "sites", "level", "digital",
  "profile", "previous", "form", "events", "love", "old", "main", "call", "device", "energy",
  "every", "create", "key", "content", "west", "sales", "look", "students", "running", "month",
  "popular", "term", "story", "options", "particularly", "computer", "food", "source", "red",
  "include", "various", "garden", "close", "code", "exit", "sites", "river", "quality", "push",
  "land", "provide", "various", "training", "credit", "matter", "usually", "money", "music",
  "field", "lot", "picture", "package", "garden", "minute", "thought", "head", "materials",
  "purpose", "example", "garden", "model", "single", "choice", "simple", "crazy", "fix", "stay",
  "talent", "screen", "weather", "fast", "engine", "behind", "laugh", "treat", "trick", "usual",
  "bright", "wonder", "gentle", "silent", "sudden", "rising", "humble", "modern", "silver",
  "golden", "gentle", "mystery", "journey", "morning", "evening", "midnight", "forever", "always",
  "tomorrow", "yesterday", "perhaps", "definitely", "absolutely", "obviously", "seriously", "simply",
  "quickly", "slowly", "carefully", "happily", "loudly", "quietly", "eagerly", "nervously", "finally",
  "computer", "keyboard", "monitor", "internet", "website", "program", "application", "software",
  "hardware", "network", "wireless", "digital", "virtual", "online", "offline", "browser", "search",
  "download", "upload", "stream", "buffer", "cache", "memory", "processor", "graphic", "display",
  "language", "python", "javascript", "function", "variable", "constant", "string", "integer",
  "boolean", "array", "object", "method", "class", "module", "package", "library", "framework",
  "database", "server", "client", "request", "response", "header", "footer", "sidebar", "content",
  "button", "dropdown", "toggle", "slider", "modal", "popup", "notification", "alert", "message",
  "rainbow", "sunset", "ocean", "mountain", "forest", "desert", "valley", "river", "island", "beach",
  "cosmic", "galaxy", "planet", "comet", "meteor", "orbit", "gravity", "energy", "quantum", "atom",
  "rhythm", "melody", "harmony", "symphony", "concert", "guitar", "piano", "drums", "violin", "trumpet",
  "hiking", "climbing", "swimming", "running", "cycling", "skiing", "surfing", "yoga", "dancing", "boxing",
  "coffee", "pizza", "burger", "sushi", "pasta", "tacos", "salad", "soup", "sandwich", "pancakes",
  "thunder", "lightning", "rainbow", "breeze", "storm", "cloudy", "sunny", "foggy", "snowy", "windy",
  "magic", "dragon", "castle", "knight", "wizard", "treasure", "quest", "journey", "adventure", "mythical"
];

export const WORDS: string[] = [...new Set(WORD_BANK)];
